name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  my_first_job:
    name: linux job
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: Build with Gradle
          run: ./gradlew build

        - name: Archive artifacts
          uses: actions/upload-artifact@v2
          with:
            name: libraries
            path: build/libs/
  my_second_job:
    name: mac job
    runs-on: 	macos-latest 
    steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: Build with Gradle
          run: ./gradlew build

        - name: Archive artifacts
          uses: actions/upload-artifact@v2
          with:
            name: libraries
            path: build/libs/
   
